version: "3.8"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3333:3000
    networks:
      - monitor
      - edge
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,jdbranham-diagram-panel,novatec-sdg-panel,camptocamp-prometheus-alertmanager-datasource
      VIRTUAL_HOST: stats.7cav.us
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: stats.7cav.us
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.4
    container_name: influxdb
    restart: always
    environment:
      VIRTUAL_HOST: influx.7cav.us
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: influx.7cav.us
    ports:
      - 9999:8086
    networks:
      - monitor
    volumes:
      - influxdb-data:/root/.influxdbv2
networks:
  monitor:
  edge:
    external: true
volumes:
  grafana-data:
    external: true
  influxdb-data:
    external: true
